# Generated by Django 3.2.3 on 2021-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobforJunes', '0005_auto_20210603_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
