# Generated by Django 3.2.3 on 2021-06-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobforJunes', '0008_auto_20210607_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Notavaible', 'Не ищу работу'),
                                                     ('Ready', 'Рассматриваю предложения'),
                                                     ('Avaible', 'Ищу работу')], default='Avaible',
                                            max_length=50)),
                ('salary', models.IntegerField()),
                ('specialty', models.TextField()),
                ('grade', models.CharField(choices=[('Trainy', 'Стажер'), ('Djunior', 'Джуниор'),
                                                    ('Middle', 'Миддл'), ('Senior', 'Сеньер'),
                                                    ('Lead', 'Лид')], default='Trainy', max_length=50)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
