# Generated by Django 3.2.3 on 2021-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobforJunes', '0009_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
